#!/usr/bin/env python3
"""Generate the Mermaid dependency graph for salted.

Writes documentation/dependency-graph-diagram.md and nothing else. The prose
around the graph lives in documentation/dependency-graph.md, which links to
the generated file - so regenerating never touches hand-written text.

What the graph shows is the **minimum** version each constraint allows, not
what happens to be installed. Those differ sharply for transitive packages
(attrs resolves to 26.x today while aiohttp only asks for >=17.3.0), and the
minimum is the number a lower-bound bump has to be checked against. Versions
are therefore derived from the constraint on the edge that pulls a package
in; where two parents constrain the same package, the higher floor wins.

Environment markers are evaluated against the interpreter running this
script, so the result describes that environment: 'colorama' arrives through
tqdm on Windows only, and pycares asks for a different cffi below Python
3.14. Regenerate on the same platform the committed graph was made on
(Windows / CPython 3.14) or expect those nodes to move.

Must be run inside the project virtualenv so the metadata of the installed
packages can be read. Use:

    poetry run python scripts/generate_dependency_graph.py
"""

import pathlib
import sys
from importlib.metadata import PackageNotFoundError, metadata
from importlib.metadata import requires as pkg_requires
from importlib.metadata import version as pkg_version

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name
from packaging.version import InvalidVersion, Version

ROOT = pathlib.Path(__file__).parent.parent
OUTPUT_FILE = ROOT / 'documentation' / 'dependency-graph-diagram.md'
ROOT_PACKAGE = 'salted'

# Extras that only bundle other extras carry no dependency of their own.
AGGREGATE_EXTRAS = frozenset({'all'})

GENERATED_NOTE = (
    '<!-- Generated by scripts/generate_dependency_graph.py - do not edit by '
    'hand. The prose belongs in dependency-graph.md. -->'
)


def _check_venv() -> None:
    """Abort if not running inside the project virtualenv."""
    running_inside_venv = (
        hasattr(sys, 'real_prefix')
        or (hasattr(sys, 'base_prefix') and sys.base_prefix != sys.prefix)
    )
    if not running_inside_venv:
        print(
            'ERROR: This script must be run inside the project virtualenv.\n'
            'Use:  poetry run python scripts/generate_dependency_graph.py',
            file=sys.stderr,
        )
        sys.exit(1)


def _active_requirements(dist: str, extra: str = '') -> list[Requirement]:
    """Requirements of `dist` that apply in this environment.

    Args:
        dist: Distribution name to read the metadata of.
        extra: The extra to resolve for. The default resolves the mandatory
            dependencies, as a marker guarding an extra is false when 'extra'
            is empty.

    Returns:
        The requirements whose marker holds, unparseable ones skipped.
    """
    active = []
    for raw in pkg_requires(dist) or []:
        try:
            req = Requirement(raw)
        except Exception:  # a malformed line must not stop the run
            print(f'WARNING: cannot parse requirement {raw!r} of {dist}',
                  file=sys.stderr)
            continue
        if req.marker is not None and not req.marker.evaluate({'extra': extra}):
            continue
        active.append(req)
    return active


def _declared_extras(dist: str) -> list[str]:
    """The extras `dist` declares, minus the ones that only bundle others."""
    provides = metadata(dist).get_all('Provides-Extra') or []
    return [e for e in provides if e not in AGGREGATE_EXTRAS]


def _display_name(dist: str, fallback: str) -> str:
    """The name a package spells itself with ('PyYAML', not 'pyyaml')."""
    try:
        return metadata(dist)['Name'] or fallback
    except PackageNotFoundError:
        return fallback


def _lower_bound(req: Requirement) -> Version | None:
    """The oldest version a constraint admits, or None if it sets no floor."""
    floors = []
    for spec in req.specifier:
        if spec.operator not in ('>=', '==', '~=', '==='):
            continue
        try:
            floors.append(Version(spec.version.rstrip('.*')))
        except InvalidVersion:
            continue
    return max(floors) if floors else None


def _constraint_label(req: Requirement) -> str:
    """The constraint as shown on an edge, lower bound first."""
    if not str(req.specifier):
        return 'any'
    specs = sorted(
        req.specifier,
        key=lambda s: (s.operator not in ('>=', '>', '==', '~=', '==='),
                       s.version))
    return ','.join(f'{s.operator}{s.version}' for s in specs)


def _walk(roots: list[tuple[str, Requirement]],
          nodes: dict,
          edges: list,
          seen: set) -> set:
    """Walk the dependency tree breadth-first from the given edges.

    Args:
        roots: (parent_node_id, requirement) pairs to start from.
        nodes: Node id -> node data; updated in place.
        edges: List of edges; appended to in place.
        seen: Node ids already expanded; updated in place.

    Returns:
        The node ids reached by this walk.
    """
    reached = set()
    queue = list(roots)
    while queue:
        parent, req = queue.pop(0)
        node_id = canonicalize_name(req.name)
        reached.add(node_id)
        edges.append({'source': parent,
                      'target': node_id,
                      'constraint': _constraint_label(req)})
        floor = _lower_bound(req)
        node = nodes.setdefault(
            node_id,
            {'display': _display_name(req.name, req.name), 'floor': None})
        # Two parents may constrain the same package: the higher floor wins.
        if floor is not None and (node['floor'] is None
                                  or floor > node['floor']):
            node['floor'] = floor
        if node_id in seen:
            continue
        seen.add(node_id)
        try:
            children = _active_requirements(req.name)
        except PackageNotFoundError:
            print(f'WARNING: {req.name} is not installed; its own '
                  'dependencies are missing from the graph', file=sys.stderr)
            continue
        queue.extend((node_id, child) for child in children)
    return reached


def build_graph() -> str:
    """Render the whole dependency graph as Mermaid source."""
    nodes: dict = {}
    edges: list = []

    root_id = canonicalize_name(ROOT_PACKAGE)
    nodes[root_id] = {'display': _display_name(ROOT_PACKAGE, ROOT_PACKAGE),
                      'floor': Version(pkg_version(ROOT_PACKAGE))}

    # Mandatory tree first, so anything it reaches counts as non-optional
    # even when an extra happens to depend on it as well.
    required = _walk(
        [(root_id, req) for req in _active_requirements(ROOT_PACKAGE)],
        nodes, edges, {root_id})
    required.add(root_id)

    optional_roots = []
    for extra in _declared_extras(ROOT_PACKAGE):
        for req in _active_requirements(ROOT_PACKAGE, extra=extra):
            # An extra is listed once per extra naming it, 'all' included.
            if any(canonicalize_name(r.name) == canonicalize_name(req.name)
                   for _, r in optional_roots):
                continue
            optional_roots.append((root_id, req))
    _walk(optional_roots, nodes, edges, set(required))

    optional_nodes = set(nodes) - required

    lines = ['flowchart TD',
             '    classDef missing stroke-dasharray: 5',
             '    classDef optional fill:#e8e8e8,stroke:#aaaaaa,'
             'color:#777777,stroke-dasharray:4']
    for node_id in sorted(nodes):
        node = nodes[node_id]
        version = str(node['floor']) if node['floor'] is not None else 'any'
        marker = ':::optional' if node_id in optional_nodes else ''
        lines.append(
            f'    {node_id}["{node["display"]}<br/>{version}"]{marker}')

    seen_edges = set()
    for edge in sorted(edges, key=lambda e: (e['source'], e['target'])):
        key = (edge['source'], edge['target'])
        if key in seen_edges:
            continue
        seen_edges.add(key)
        if edge['target'] in optional_nodes:
            lines.append(f'    {edge["source"]} -. "{edge["constraint"]}" '
                         f'.-> {edge["target"]}')
        else:
            lines.append(f'    {edge["source"]} -- "{edge["constraint"]}" '
                         f'--> {edge["target"]}')
    return '\n'.join(lines)


def main() -> None:
    _check_venv()
    mermaid = build_graph()
    OUTPUT_FILE.write_text(
        f'{GENERATED_NOTE}\n\n```mermaid\n{mermaid}\n```\n', encoding='utf-8')
    print(f'Written to {OUTPUT_FILE}')


if __name__ == '__main__':
    main()
