 # The code has type annotations. Enforce correctness of those.

name: Mypy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:

    - name: APT Update
      run: sudo apt update

    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies and Mypy
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install mypy

    - name: Check code with Mypy
      run: mypy salted/
